landoceandataset:
  dataset:
    num_classes: 1
    num_samples: 100000
    batch_size: 512
    addcoastline: false
    dropout: false
  slepian-siren:
    dim_hidden: 32
    lr: 0.00010069783877453494
    num_layers: 3
    wd: 1.0012966815467706e-08
    max_epochs: 150
  sphericalharmonics-siren:
    dim_hidden: 32
    lr: 0.00010069783877453494
    num_layers: 3
    wd: 1.0012966815467706e-08
    max_epochs: 150
  slepianhybrid-siren:
    dim_hidden: 32
    lr: 0.00010069783877453494
    num_layers: 3
    wd: 1.0012966815467706e-08
    max_epochs: 150
  slepian-mlp:
    dim_hidden: 256
    lr: 0.001
    num_layers: 3
    wd: 0.0
    max_epochs: 50
  sphericalharmonics-mlp:
    dim_hidden: 256
    lr: 0.001
    num_layers: 3
    wd: 0.0
    max_epochs: 50
  slepianhybrid-mlp:
    dim_hidden: 256
    lr: 0.001
    num_layers: 3
    wd: 0.0
    max_epochs: 50
  cossin-mlp:
    dim_hidden: 256
    lr: 0.001
    num_layers: 3
    wd: 0.0
    max_epochs: 50
highreslandoceandataset:
  dataset:
    num_classes: 1
    num_samples: 10000
    batch_size: 256
    addcoastline: false
    dropout: false
  slepian-siren:
    dim_hidden: 32
    lr: 0.00010069783877453494
    num_layers: 3
    wd: 1.0012966815467706e-08
    max_epochs: 150
  sphericalharmonics-siren:
    dim_hidden: 32
    lr: 0.00010069783877453494
    num_layers: 3
    wd: 1.0012966815467706e-08
    max_epochs: 150
  slepianhybrid-siren:
    dim_hidden: 32
    lr: 0.00010069783877453494
    num_layers: 3
    wd: 1.0012966815467706e-08
    max_epochs: 150
  slepian-mlp:
    dim_hidden: 256
    lr: 0.001
    num_layers: 3
    wd: 0.0
    max_epochs: 500
  sphericalharmonics-mlp:
    dim_hidden: 256
    lr: 0.001
    num_layers: 3
    wd: 0.0
    max_epochs: 500
  slepianhybrid-mlp:
    dim_hidden: 256
    lr: 0.001
    num_layers: 3
    wd: 0.0
    max_epochs: 500
  cossin-mlp:
    dim_hidden: 256
    lr: 0.001
    num_layers: 3
    wd: 0.0
    max_epochs: 500
  direct-mlp:
    dim_hidden: 256
    lr: 0.001
    num_layers: 3
    wd: 0.0
    max_epochs: 500